import type { Company, Job } from "@/types";

export const POPULAR_CATEGORIES = [
  { label: "Software Development", value: "development" },
  { label: "Design", value: "design" },
  { label: "Marketing", value: "marketing" },
  { label: "Finance", value: "finance" },
  { label: "Product", value: "product" },
  { label: "Customer Support", value: "customer-support" },
  { label: "Data", value: "data" },
  { label: "Operations", value: "operations" },
] as const;

export const PLATFORM_STATS = [
  { label: "Jobs", value: "10K+" },
  { label: "Companies", value: "5K+" },
  { label: "Candidates", value: "25K+" },
  { label: "Satisfaction", value: "95%" },
] as const;

function mockCompany(name: string, industry: string): Company {
  return {
    _id: name.toLowerCase().replace(/\s+/g, "-"),
    name,
    industry,
    location: "Remote",
    owner: "seed",
    createdAt: new Date().toISOString(),
    verified: true,
  };
}

/** Demo cards used only when the jobs API has no approved listings yet. */
export const MOCK_FEATURED_JOBS: Job[] = [
  {
    _id: "mock-frontend",
    title: "Frontend Developer",
    description: "Build accessible product interfaces with React and Next.js.",
    company: mockCompany("Northwind Studio", "Software"),
    employer: "seed",
    location: "Remote",
    workplace: "remote",
    jobType: "full-time",
    experienceLevel: "mid",
    salary: { min: 1500, max: 2500, currency: "USD" },
    skills: ["React", "Next.js", "TypeScript"],
    category: "development",
    status: "approved",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "mock-next",
    title: "Next.js Developer",
    description: "Own the candidate-facing web experience and design system.",
    company: mockCompany("ABC Software", "Software"),
    employer: "seed",
    location: "Karachi",
    workplace: "hybrid",
    jobType: "full-time",
    experienceLevel: "senior",
    salary: { min: 2500, max: 4000, currency: "USD" },
    skills: ["Next.js", "React", "Tailwind"],
    category: "development",
    status: "approved",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "mock-backend",
    title: "Backend Developer",
    description: "Design APIs, hiring workflows, and MongoDB data models.",
    company: mockCompany("Harbor Labs", "Software"),
    employer: "seed",
    location: "Lahore",
    workplace: "onsite",
    jobType: "full-time",
    experienceLevel: "mid",
    salary: { min: 1800, max: 2800, currency: "USD" },
    skills: ["Node.js", "Express", "MongoDB"],
    category: "development",
    status: "approved",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "mock-product",
    title: "Product Designer",
    description: "Shape dashboards, empty states, and a calm hiring language.",
    company: mockCompany("Lumen", "Design"),
    employer: "seed",
    location: "Dubai",
    workplace: "hybrid",
    jobType: "full-time",
    experienceLevel: "mid",
    salary: { min: 2000, max: 3200, currency: "USD" },
    skills: ["Figma", "UI", "Prototyping"],
    category: "design",
    status: "approved",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "mock-data",
    title: "Data Analyst",
    description: "Turn application funnels into decisions hiring teams can trust.",
    company: mockCompany("Atlas People", "Data"),
    employer: "seed",
    location: "Remote",
    workplace: "remote",
    jobType: "full-time",
    experienceLevel: "junior",
    salary: { min: 1400, max: 2200, currency: "USD" },
    skills: ["SQL", "Python", "Looker"],
    category: "data",
    status: "approved",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "mock-talent",
    title: "Talent Partner",
    description: "Run structured hiring loops and keep candidates informed.",
    company: mockCompany("Kindred", "Human Resources"),
    employer: "seed",
    location: "Islamabad",
    workplace: "onsite",
    jobType: "full-time",
    experienceLevel: "junior",
    salary: { min: 1600, max: 2400, currency: "USD" },
    skills: ["Recruiting", "Communication"],
    category: "human-resources",
    status: "approved",
    createdAt: new Date().toISOString(),
  },
];
